Repository adrianpdm/demo-intuit-auto, pull requests merged in 2021-09, with the labels that each got.

#1 making pull request test
  edit.txt
Labels: minor

#3 test skipping patch
  edit.txt
Labels: patch

#4 test skipping patch #2
  edit.txt
Labels: patch, skip-release, internal

#5 debug: current and latest version comparison
  .github/workflows/release.yml
Labels: bug, skip-release

#6 ci: fix package.json current version interpolation
  .github/workflows/release.yml
Labels: patch
